### PR TITLE
Expose RuntimeContainer.Labels

### PR DESCRIPTION
**Pull request by md5**
Related: jwilder/docker-gen#81

### CODE REVIEW

**Comment by jwilder** [comment]
@md5 nice! Been meaning to add this but haven't had time.  Need to test it out but looks pretty straightforward.

**Comment by md5** [comment]
:+1:

**Comment by thaJeztah** [comment]
Great!


*/me should suggest to add @md5 as maintainer to this and the nginx-proxy repos*

**Comment by tompson** [comment]
Is there a sample somewhere on how to use labels in a template? I somehow can not get it to work

**Comment by tompson** [comment]
The problem is that the labels generated by compose are looking like 

```com.docker.compose.service```

How do you access them in the template?

**Comment by md5** [comment]
I believe `index .Env.Labels "com.docker.compose.service"` should work.

**Comment by trnubo** [comment]
Sorry if this is the wrong place to ask. How would you use a label such as "com.docker.compose.service" in as part of a $fieldPath with a groupBy or where?

`where . "Labels.com.docker.compose.service" "web"`

**Comment by md5** [comment]
@trnubo I don't think it's going to be possible to do that right now. I also think it would be tricky to get right.

Adding `groupByLabel` and `whereLabel` functions might not be the worst idea, although it would balloon pretty quickly if you add `*Label` variants of all the existing `where*` and `groupBy*` functions.

**Comment by md5** [comment]
@trnubo Take a look at https://github.com/jwilder/docker-gen/pull/143

**Comment by md5** [comment]
For the case you mentioned, you could do this:

```
whereLabelValueMatches . "com.docker.compose.service" "^web$"
```

**Comment by helderco** [comment]
What's wrong here?

```
{{ range $host, $containers := groupByMulti $ "Env.VIRTUAL_HOST" "," }}
{{ $project := index $.Labels "com.docker.compose.project" }}
...
```

I get this error: `template error: template: nginx.tmpl:61:22: executing "nginx.tmpl" at <$.Labels>: can't evaluate field Labels in type *dockergen.Context`

**Pull request merged**
