### PR TITLE
Where primitives

### PR DESCRIPTION
**Pull request by dataferret**
Related to Issue #26. I added intersect (slice vs slice compare), and a few where functions that utilize it to match.

### CODE REVIEW

**Comment by md5** [comment]
:+1:

**Comment by md5** [comment]
@dataferret just saw your comment on #26. I just pushed [an old commit](https://github.com/md5/docker-gen/commit/f6144b8545657f0eb6f5ed90607c658f1bf87daa) I had locally for using `Where` from `hugolib`, but I think just implementing it directly like you did is better.

**Comment by jwilder** [comment]
This is nice.  What do you think about some slightly different names?  

* `whereSomeMatch` -> `whereAny`
* `whereRequires` -> `whereAll`

**Comment by dataferret** [comment]
Those names sound good.  You want to do it your end or should I resubmit the PR?

**Comment by jwilder** [comment]
Merged w/ bcddaab30.  Thanks!

**Pull request closed without merging**
