### PR TITLE
fixes #99

### LINKED ISSUE #99: Must pass an array or slice to 'whereExist'
Hi,

What am I doing wrong?

```bash
$ docker run --rm -ti jwilder/docker-gen -version
0.4.0
```

logstash-forwarder.json.tmpl:
```
{{whereExist . "Labels.logs" | len}}
```

```bash
$ docker run --rm -ti -v `pwd`/templates:/templates -v /var/run/docker.sock:/tmp/docker.sock jwilder/docker-gen -watch /templates/logstash-forwarder.json.tmpl /etc/logstash-forwarder.json
2015/07/16 07:13:41 template error: template: logstash-forwarder.json.tmpl:1:2: executing "logstash-forwarder.json.tmpl" at <whereExist . "Labels...>: error calling whereExist: Must pass an array or slice to 'whereExist'; received &[0xc208000d80 0xc208001560 0xc2080017a0 0xc208001c20 0xc2080a2120 0xc2080a2360 0xc2080a26c0 0xc2080a2b40 0xc2080a2fc0]
```

### PR DESCRIPTION
**Pull request by ybogdanov**
fixes #99

### CODE REVIEW

**Comment by jwilder** [comment]
Can you rebase?

**Comment by md5** [comment]
It looks like a simple rebase won't be enough since the code has changed substantially. However, this PR could be repurposed for a couple of fixes I mentioned in some comments on #97 since I think `master` still has the same issue reported in #99.

@ybogdanov What do you think?

**Comment by ybogdanov** [comment]
Hey, looks like #97 and #101 makes this PR nonsense. Close?

**Comment by jwilder** [comment]
I believe this has been addressed by other PRs.

**Pull request closed without merging**
