### PR TITLE
Added nginx-ssl-include.tmpl template optimized for ownCloud and Seafile.

### PR DESCRIPTION
**Pull request by ypid**
Example usage: https://github.com/ypid/docker-makefile/blob/master/Makefile

### CODE REVIEW

**Comment by jwilder** [comment]
Not sure if you meant to make a change for `nginx-proxy` or just add this as an example template.  This is too specific to include in `nginx-proxy` though.

**Comment by ypid** [comment]
I wanted to add another, more suphisticated example. Should I submit it to https://github.com/jwilder/nginx-proxy instead?

**Comment by jwilder** [comment]
Ok.  Can you name the template after the package it's for and add it to the `templates` dir?  See: https://github.com/jwilder/docker-gen/tree/master/templates for other examples.

**Comment by ypid** [comment]
OK.

**Comment by ypid** [comment]
Any news?

**Pull request closed without merging**
