### PR TITLE
Include information about the swarm node a container is on.

### PR DESCRIPTION
**Pull request by JustAdam**

### CODE REVIEW

**Comment by md5** [comment]
@JustAdam I think you might need to update docker/docker to the same ref that fsouza/go-dockerclient has in order to fix that Travis failure.

**Comment by JustAdam** [comment]
Thanks @md5 got that fixed with the latest commit from Docker.

**Comment by md5** [comment]
:+1:

**Comment by jwilder** [comment]
Thanks!

**Pull request merged**
